---
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# Global config
global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: caddy
    static_configs:
      - targets:
          - caddy:2019

  - job_name: blackbox_exporter_http_probes
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          # Alphabetical by primary domain
          - https://ps2.fisu.pw
          - https://wt.honu.pw
          - https://census.lithafalcon.cc/get/ps2
          - https://ps2alerts.com
          - https://api.ps2alerts.com
          - https://nanite-systems.net
          - https://outfit-tracker.com
          - https://ps2.live
          - https://recursiontracker.com
          - https://voidwell.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
